### ISSUE TITLE
is the project Dead? :(

### ISSUE THREAD

**Issue by qamichele594** [Gericom/GBARunner2#261] opened 2022-01-31 00:41 UTC
if there is a way can i help (i dont know programming :( ) i offer as many help as i can . i offer you some testing :o image editting or anything can i help :o i also thank you for all your hard work :) and for bringing this awesome tool :)

**Comment by RocketRobz** [comment] 2022-01-31 00:55
Duplicate of https://github.com/Gericom/GBARunner2/issues/6

An exact duplicate. :P

**Comment by qamichele594** [comment] 2022-01-31 00:56
R.I.P. my GBARunner2 2016-2022(!), should to be solution is to use VC injects or open_agb_firm or (only on N3DS) mGBA.

**Comment by RocketRobz** [comment] 2022-01-31 00:58
Didn't say that it was dead. Look at @Gericom's reply in the issue I linked, which I will post here, since you probably won't click it.
> No, it's not dead. I'm just busy with my study atm. I'll work on this project again when I have the time to do so.

**Comment by qamichele594** [comment] 2022-01-31 01:00
> Didn't say that it was dead. Look at @Gericom's reply in the issue I linked, which I will post here, since you probably won't click it.
> 
> > No, it's not dead. I'm just busy with my study atm. I'll work on this project again when I have the time to do so.

Yes, it's dead, just use VBA-M or open_agb_firm or VC Injects or (only on N3DS) mGBA instead for this one.

**Comment by RocketRobz** [comment] 2022-01-31 01:31
> Yes, it's dead, just use VBA-M or open_agb_firm or VC Injects or (only on N3DS) mGBA instead for this one.

I see...
Since it's dead (as you claim, instead of the main dev himself), will you stop opening issues in this repo, and stick to the alternatives suggested to you in the past?

If you can answer the above question properly, your account will be kept.
If you avoid the above question, your account will be reported, and then deleted by GitHub, like with your earlier accounts.

**Comment by qamichele594** [comment] 2022-01-31 01:35
> > Yes, it's dead, just use VBA-M or open_agb_firm or VC Injects or (only on N3DS) mGBA instead for this one.
> 
> I see... Since it's dead (as you claim, instead of the main dev himself), will you stop opening issues in this repo, and stick to the alternatives suggested to you in the past?
> 
> If you can answer the above question properly, your account will be kept. If you avoid the above question, your account will be reported, and then deleted by GitHub, like with your earlier accounts.

Account don't delete me!!!!

**Closed** 2022-01-31 01:35 UTC

**Comment by qamichele594** [comment] 2022-01-31 01:50
my github account don't delete me!!!!!!!!

Il giorno lun 31 gen 2022 alle ore 02:31 RocketRobz <
***@***.***> ha scritto:

**Comment by RocketRobz** [comment] 2022-01-31 02:11
> Account won't delete me!!!! Account won't report me!!!! Account won't kept me!!!!

All of your posts have ever done is annoy people, and is evident by you avoiding help from those who try to.
If you don't know or understand how to do what's suggested by others, I once again, tell you to ask how to do it, instead of avoiding help of which you continuously request.

If you're going to continue avoiding help, then you have no choice in the matter, and to do what's stated as follows:

Please stop opening new issues, stop posting in ones opened by other people, and close all of the ones you opened earlier in all places of GitHub (including the GBARunner2 repo).

Failure to do so *will* get your account reported and deleted, and this being my last reply to you.
Don't want it to happen to your account? Then do either of what I stated above.

**Comment by qamichele594** [comment] 2022-01-31 03:53
> > Account won't delete me!!!! Account won't report me!!!! Account won't kept me!!!!
> 
> All of your posts have ever done is annoy people, and is evident by you avoiding help from those who try to. If you don't know or understand how to do what's suggested by others, I once again, tell you to ask how to do it, instead of avoiding help of which you continuously request.
> 
> If you're going to continue avoiding help, then you have no choice in the matter, and to do what's stated as follows:
> 
> Please stop opening new issues, stop posting in ones opened by other people, and close all of the ones you opened earlier in all places of GitHub (including the GBARunner2 repo).
> 
> Failure to do so _will_ get your account reported and deleted, and this being my last reply to you. Don't want it to happen to your account? Then do either of what I stated above.

Account won't delete me!!!! Account won't report me!!!! Account won't kept me!!!!
