### ISSUE TITLE
TAFNN  IO Library

### ISSUE THREAD

**Issue by antgeth** [Gericom/GBARunner2#38] opened 2019-03-22 00:43 UTC
was excited to try this out, but all i get is white screens with that message, and, as seems to always be the case for me, no one else seems to have had this issue.

using an r4i on DSL. (also tried it on an SD card via HiyaCFI on a DSiXL but that came up with an entirely different error, and i'd like the flexibility of using it on either console)

**Comment by RocketRobz** [comment] 2019-06-09 05:01
I believe the issue is fixed on latest commit.

**Comment by Gericom** [comment] 2019-06-10 10:04
I guess so. But if there's now an error with initializing dldi it would white screen instead (might need to fix that lol). Error initializing fat now gives a nice error on screen at least.

**Closed by Gericom** 2019-06-10 10:04 UTC

**Comment by antgeth** [comment] 2019-06-12 00:15
the issue is fixed (hooray!).  now i just get black screens when trying to load any rom.

progress, at least!
